#!/bin/sh

against=`git rev-parse --verify HEAD 2>/dev/null || echo 4b825dc642cb6eb9a060e54bf8d69288fbee4904`

if ! git diff --cached --name-only --diff-filter=ACMRTUXB -z $against |tr '\0' '\012' | check-lint
then
	exit 1
fi
