#!/bin/sh
# Check for white-space strangeness (space before tab, etc):

against=`git rev-parse --verify HEAD 2>/dev/null || echo 4b825dc642cb6eb9a060e54bf8d69288fbee4904`
echo "Checking for strange white-space"

exec git diff-index --check --cached $against --
